server:
  port: 18083
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
        port: 8179
  zipkin:
    base-url: http://127.0.0.1:9411
    locator:
      discovery:
        enabled: true
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.72.140/guli_wms
    username: root
    password: root
  redis:
    host: 127.0.0.1
feign:
  sentinel:
    enabled: true
mybatis-plus:
  mapper-locations: classpath:mapper/wms/**/*.xml
  type-aliases-package: com.atguigu.gmall.wms.entity
  global-config:
    id-type: auto

